<?php

//Create Student Conatcts Importer Table 
if(!Database::tableExists('STUDENT_CONTACTS_IMPORTER_TABLE')){
	Database::query("CREATE TABLE STUDENT_CONTACTS_IMPORTER_TABLE(
					STUDENT_ID VARCHAR(255), 
					RELATION VARCHAR(255), 
					PRIORITY VARCHAR(255), 
					FIRST_NAME VARCHAR(255), 
					LAST_NAME VARCHAR(255), 
					MIDDLE_NAME VARCHAR(255), 
					ADDRESS VARCHAR(255), 
					ADDRESS2 VARCHAR(255), 
					CITY VARCHAR(255), 
					STATE VARCHAR(255), 
					ZIPCODE VARCHAR(255), 
					RESIDES_WITH_STUD VARCHAR(255), 
					CUSTODY VARCHAR(255), 
					EMERGENCY VARCHAR(255), 
					WORK_PH VARCHAR(255), 
					CELL_PH VARCHAR(255), 
					EMPLOYER VARCHAR(255), 
					EMP_ADDRESS VARCHAR(255), 
					OTHER_PHONE1 VARCHAR(255), 
					OTHER_PHONE2 VARCHAR(255), 
					CALLOUT_PH VARCHAR(255), 
					EMAIL_PRIM VARCHAR(255), 
					EMAIL_SEC VARCHAR(255), 
					ADDRESS_PHONE VARCHAR(255), 
					CONTACT1_TYPE VARCHAR(255), 
					CONTACT1_VALUE VARCHAR(255), 
					CONTACT2_TYPE VARCHAR(255), 
					CONTACT2_VALUE VARCHAR(255), 
					CONTACT3_TYPE VARCHAR(255), 
					CONTACT3_VALUE VARCHAR(255), 
					CONTACT4_TYPE VARCHAR(255), 
					CONTACT4_VALUE VARCHAR(255), 
					CONTACT5_TYPE VARCHAR(255), 
					CONTACT5_VALUE VARCHAR(255), 
					CONTACT6_TYPE VARCHAR(255), 
					CONTACT6_VALUE VARCHAR(255), 
					CONTACT7_TYPE VARCHAR(255), 
					CONTACT7_VALUE VARCHAR(255)
					);");
}

Database::query( "update 
				  importer_keys 
				  set required_fields = '[\"mp\"]'
                  where table_name = 'schedule'");
