<?php
// Update the LOG_FIELD3, LOG_FIELD4, LOG_FIELD5, and LOG_FIELD12 ESE Exceptionality columns to be system fields.

$sql = "
	UPDATE
		CUSTOM_FIELD_LOG_COLUMNS
	SET
		SYSTEM = 1
	WHERE
		ID
	IN (
		SELECT
			CUSTOM_FIELD_LOG_COLUMNS.ID
		FROM 
			CUSTOM_FIELDS
		JOIN
			CUSTOM_FIELD_LOG_COLUMNS 
			ON 
				CUSTOM_FIELDS.ID = CUSTOM_FIELD_LOG_COLUMNS.FIELD_ID
			AND
				CUSTOM_FIELDS.ALIAS = 'primary_exceptionality'
			AND (
					CUSTOM_FIELD_LOG_COLUMNS.COLUMN_NAME = 'LOG_FIELD3'
				OR
					CUSTOM_FIELD_LOG_COLUMNS.COLUMN_NAME = 'LOG_FIELD4'
				OR
					CUSTOM_FIELD_LOG_COLUMNS.COLUMN_NAME = 'LOG_FIELD5'
				OR
					CUSTOM_FIELD_LOG_COLUMNS.COLUMN_NAME = 'LOG_FIELD12'
			)
	);
";

Database::query($sql);
